/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.squareup.moshi.Json

/**
 * Abstract webhook payload. Use the correct payload type for your webhook event type in order to access all the specific properties for that event. See the `NEW_EMAIL`,`NEW_CONTACT`, `NEW_ATTACHMENT` and `EMAIL_OPENED` payloads for the properties available for those events.
 * @param eventName 
 * @param messageId 
 * @param webhookId 
 * @param webhookName 
 */

data class AbstractWebhookPayload (
    @Json(name = "eventName")
    val eventName: AbstractWebhookPayload.EventName,
    @Json(name = "messageId")
    val messageId: kotlin.String,
    @Json(name = "webhookId")
    val webhookId: java.util.UUID,
    @Json(name = "webhookName")
    val webhookName: kotlin.String? = null
) {

    /**
     * 
     * Values: EMAIL_RECEIVED,NEW_EMAIL,NEW_CONTACT,NEW_ATTACHMENT,EMAIL_OPENED,EMAIL_READ,BOUNCE,BOUNCE_RECIPIENT,NEW_SMS
     */
    enum class EventName(val value: kotlin.String) {
        @Json(name = "EMAIL_RECEIVED") EMAIL_RECEIVED("EMAIL_RECEIVED"),
        @Json(name = "NEW_EMAIL") NEW_EMAIL("NEW_EMAIL"),
        @Json(name = "NEW_CONTACT") NEW_CONTACT("NEW_CONTACT"),
        @Json(name = "NEW_ATTACHMENT") NEW_ATTACHMENT("NEW_ATTACHMENT"),
        @Json(name = "EMAIL_OPENED") EMAIL_OPENED("EMAIL_OPENED"),
        @Json(name = "EMAIL_READ") EMAIL_READ("EMAIL_READ"),
        @Json(name = "BOUNCE") BOUNCE("BOUNCE"),
        @Json(name = "BOUNCE_RECIPIENT") BOUNCE_RECIPIENT("BOUNCE_RECIPIENT"),
        @Json(name = "NEW_SMS") NEW_SMS("NEW_SMS");
    }
}

