/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.squareup.moshi.Json

/**
 * 
 * @param createdAt 
 * @param updatedAt 
 * @param userId 
 * @param attachmentId Attachment ID
 * @param contentLength Content length of attachment in bytes
 * @param contentType Content type of attachment.
 * @param name 
 */

data class AttachmentProjection (
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,
    @Json(name = "userId")
    val userId: java.util.UUID,
    /* Attachment ID */
    @Json(name = "attachmentId")
    val attachmentId: kotlin.String? = null,
    /* Content length of attachment in bytes */
    @Json(name = "contentLength")
    val contentLength: kotlin.Long? = null,
    /* Content type of attachment. */
    @Json(name = "contentType")
    val contentType: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null
)

