/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.google.gson.annotations.SerializedName

/**
 * Bounced recipient
 * @param createdAt 
 * @param recipient 
 * @param id 
 * @param action 
 * @param status 
 * @param sentEmailId 
 */

data class BounceRecipientProjection (
    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime,
    @SerializedName("recipient")
    val recipient: kotlin.String,
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("action")
    val action: kotlin.String? = null,
    @SerializedName("status")
    val status: kotlin.String? = null,
    @SerializedName("sentEmailId")
    val sentEmailId: java.util.UUID? = null
)

