/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param customerName 
 * @param address1 
 * @param city 
 * @param region 
 * @param postalCode 
 * @param isoCountryCode 
 * @param displayName 
 */

data class CreateEmergencyAddressOptions (
    @SerializedName("customerName")
    val customerName: kotlin.String,
    @SerializedName("address1")
    val address1: kotlin.String,
    @SerializedName("city")
    val city: kotlin.String,
    @SerializedName("region")
    val region: kotlin.String,
    @SerializedName("postalCode")
    val postalCode: kotlin.String,
    @SerializedName("isoCountryCode")
    val isoCountryCode: CreateEmergencyAddressOptions.IsoCountryCode,
    @SerializedName("displayName")
    val displayName: kotlin.String? = null
) {

    /**
     * 
     * Values: US,GB
     */
    enum class IsoCountryCode(val value: kotlin.String) {
        @SerializedName(value = "US") US("US"),
        @SerializedName(value = "GB") GB("GB");
    }
}

