/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.google.gson.annotations.SerializedName

/**
 * Preview object for domain entity
 * @param id 
 * @param domain 
 * @param createdAt 
 * @param domainType Type of domain. Dictates type of inbox that can be created with domain. HTTP means inboxes are processed using SES while SMTP inboxes use a custom SMTP mail server. SMTP does not support sending so use HTTP for sending emails.
 * @param isVerified 
 * @param catchAllInboxId 
 */

data class DomainPreview (
    @SerializedName("id")
    val id: java.util.UUID,
    @SerializedName("domain")
    val domain: kotlin.String,
    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime,
    /* Type of domain. Dictates type of inbox that can be created with domain. HTTP means inboxes are processed using SES while SMTP inboxes use a custom SMTP mail server. SMTP does not support sending so use HTTP for sending emails. */
    @SerializedName("domainType")
    val domainType: DomainPreview.DomainType,
    @SerializedName("isVerified")
    val isVerified: kotlin.Boolean,
    @SerializedName("catchAllInboxId")
    val catchAllInboxId: java.util.UUID? = null
) {

    /**
     * Type of domain. Dictates type of inbox that can be created with domain. HTTP means inboxes are processed using SES while SMTP inboxes use a custom SMTP mail server. SMTP does not support sending so use HTTP for sending emails.
     * Values: HTTP_INBOX,SMTP_DOMAIN
     */
    enum class DomainType(val value: kotlin.String) {
        @SerializedName(value = "HTTP_INBOX") HTTP_INBOX("HTTP_INBOX"),
        @SerializedName(value = "SMTP_DOMAIN") SMTP_DOMAIN("SMTP_DOMAIN");
    }
}

