/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
*
* The version of the OpenAPI document: 6.5.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.squareup.moshi.Json
/**
 * Content of attachment
 * @param base64FileContents Base64 encoded string of attachment bytes. Decode the base64 string to get the raw file bytes
 * @param contentType Content type of attachment
 * @param sizeBytes Size in bytes of attachment
 */

data class DownloadAttachmentDto (
    /* Base64 encoded string of attachment bytes. Decode the base64 string to get the raw file bytes */
    @Json(name = "base64FileContents")
    val base64FileContents: kotlin.String? = null,
    /* Content type of attachment */
    @Json(name = "contentType")
    val contentType: kotlin.String? = null,
    /* Size in bytes of attachment */
    @Json(name = "sizeBytes")
    val sizeBytes: kotlin.Long? = null
)

