/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.squareup.moshi.Json

/**
 * Tracking pixel
 * @param id 
 * @param seen 
 * @param html 
 * @param url 
 * @param createdAt 
 * @param recipient 
 * @param inboxId 
 * @param sentEmailId 
 * @param seenAt 
 */

data class TrackingPixelDto (
    @Json(name = "id")
    val id: java.util.UUID,
    @Json(name = "seen")
    val seen: kotlin.Boolean,
    @Json(name = "html")
    val html: kotlin.String,
    @Json(name = "url")
    val url: kotlin.String,
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,
    @Json(name = "recipient")
    val recipient: kotlin.String? = null,
    @Json(name = "inboxId")
    val inboxId: java.util.UUID? = null,
    @Json(name = "sentEmailId")
    val sentEmailId: java.util.UUID? = null,
    @Json(name = "seenAt")
    val seenAt: java.time.OffsetDateTime? = null
)

