/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param emailAddress 
 * @param accountState 
 * @param accountType 
 * @param createdAt 
 * @param subscriptionType 
 */

data class UserInfoDto (
    @Json(name = "id")
    val id: java.util.UUID,
    @Json(name = "emailAddress")
    val emailAddress: kotlin.String,
    @Json(name = "accountState")
    val accountState: UserInfoDto.AccountState,
    @Json(name = "accountType")
    val accountType: UserInfoDto.AccountType,
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,
    @Json(name = "subscriptionType")
    val subscriptionType: UserInfoDto.SubscriptionType? = null
) {

    /**
     * 
     * Values: fROZEN,aCTIVE
     */
    enum class AccountState(val value: kotlin.String) {
        @Json(name = "FROZEN") fROZEN("FROZEN"),
        @Json(name = "ACTIVE") aCTIVE("ACTIVE");
    }
    /**
     * 
     * Values: sOLO,cHILDSOLO,cHILDTEAM
     */
    enum class AccountType(val value: kotlin.String) {
        @Json(name = "SOLO") sOLO("SOLO"),
        @Json(name = "CHILD_SOLO") cHILDSOLO("CHILD_SOLO"),
        @Json(name = "CHILD_TEAM") cHILDTEAM("CHILD_TEAM");
    }
    /**
     * 
     * Values: pROMONTHLY,sTARTER,tEAM,eNTERPRISE
     */
    enum class SubscriptionType(val value: kotlin.String) {
        @Json(name = "PRO_MONTHLY") pROMONTHLY("PRO_MONTHLY"),
        @Json(name = "STARTER") sTARTER("STARTER"),
        @Json(name = "TEAM") tEAM("TEAM"),
        @Json(name = "ENTERPRISE") eNTERPRISE("ENTERPRISE");
    }
}

