/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.squareup.moshi.Json

/**
 * Result of a webhook notification
 * @param userId 
 * @param webhookId 
 * @param webhookUrl 
 * @param messageId 
 * @param httpMethod 
 * @param webhookEvent 
 * @param responseTimeMillis 
 * @param createdAt 
 * @param updatedAt 
 * @param seen 
 * @param id 
 * @param inboxId 
 * @param redriveId 
 * @param responseStatus 
 * @param responseBodyExtract 
 * @param resultType 
 */

data class WebhookResultDto (
    @Json(name = "userId")
    val userId: java.util.UUID,
    @Json(name = "webhookId")
    val webhookId: java.util.UUID,
    @Json(name = "webhookUrl")
    val webhookUrl: kotlin.String,
    @Json(name = "messageId")
    val messageId: kotlin.String,
    @Json(name = "httpMethod")
    val httpMethod: WebhookResultDto.HttpMethod,
    @Json(name = "webhookEvent")
    val webhookEvent: WebhookResultDto.WebhookEvent,
    @Json(name = "responseTimeMillis")
    val responseTimeMillis: kotlin.Long,
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,
    @Json(name = "seen")
    val seen: kotlin.Boolean,
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "inboxId")
    val inboxId: java.util.UUID? = null,
    @Json(name = "redriveId")
    val redriveId: java.util.UUID? = null,
    @Json(name = "responseStatus")
    val responseStatus: kotlin.Int? = null,
    @Json(name = "responseBodyExtract")
    val responseBodyExtract: kotlin.String? = null,
    @Json(name = "resultType")
    val resultType: WebhookResultDto.ResultType? = null
) {

    /**
     * 
     * Values: GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS,TRACE
     */
    enum class HttpMethod(val value: kotlin.String) {
        @Json(name = "GET") GET("GET"),
        @Json(name = "HEAD") HEAD("HEAD"),
        @Json(name = "POST") POST("POST"),
        @Json(name = "PUT") PUT("PUT"),
        @Json(name = "PATCH") PATCH("PATCH"),
        @Json(name = "DELETE") DELETE("DELETE"),
        @Json(name = "OPTIONS") OPTIONS("OPTIONS"),
        @Json(name = "TRACE") TRACE("TRACE");
    }
    /**
     * 
     * Values: EMAIL_RECEIVED,NEW_EMAIL,NEW_CONTACT,NEW_ATTACHMENT,EMAIL_OPENED,EMAIL_READ,BOUNCE,BOUNCE_RECIPIENT,NEW_SMS
     */
    enum class WebhookEvent(val value: kotlin.String) {
        @Json(name = "EMAIL_RECEIVED") EMAIL_RECEIVED("EMAIL_RECEIVED"),
        @Json(name = "NEW_EMAIL") NEW_EMAIL("NEW_EMAIL"),
        @Json(name = "NEW_CONTACT") NEW_CONTACT("NEW_CONTACT"),
        @Json(name = "NEW_ATTACHMENT") NEW_ATTACHMENT("NEW_ATTACHMENT"),
        @Json(name = "EMAIL_OPENED") EMAIL_OPENED("EMAIL_OPENED"),
        @Json(name = "EMAIL_READ") EMAIL_READ("EMAIL_READ"),
        @Json(name = "BOUNCE") BOUNCE("BOUNCE"),
        @Json(name = "BOUNCE_RECIPIENT") BOUNCE_RECIPIENT("BOUNCE_RECIPIENT"),
        @Json(name = "NEW_SMS") NEW_SMS("NEW_SMS");
    }
    /**
     * 
     * Values: BAD_RESPONSE,EXCEPTION,SUCCESS
     */
    enum class ResultType(val value: kotlin.String) {
        @Json(name = "BAD_RESPONSE") BAD_RESPONSE("BAD_RESPONSE"),
        @Json(name = "EXCEPTION") EXCEPTION("EXCEPTION"),
        @Json(name = "SUCCESS") SUCCESS("SUCCESS");
    }
}

