/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models

import com.mailslurp.models.WebhookHeaders

import com.squareup.moshi.Json

/**
 * Representation of a webhook for an inbox. The URL specified will be using by MailSlurp whenever an email is received by the attached inbox. A webhook entity should have a URL that points to your server. Your server should accept HTTP/S POST requests and return a success 200. MailSlurp will retry your webhooks if they fail. See https://api.mailslurp.com/schemas/webhook-payload for the payload schema.
 * @param id ID of the Webhook
 * @param userId User ID of the Webhook
 * @param basicAuth Does webhook expect basic authentication? If true it means you created this webhook with a username and password. MailSlurp will use these in the URL to authenticate itself.
 * @param url URL of your server that the webhook will be sent to. The schema of the JSON that is sent is described by the payloadJsonSchema.
 * @param method HTTP method that your server endpoint must listen for
 * @param payloadJsonSchema Deprecated. Fetch JSON Schema for webhook using the getJsonSchemaForWebhookPayload method
 * @param createdAt When the webhook was created
 * @param updatedAt 
 * @param name Name of the webhook
 * @param inboxId The inbox that the Webhook will be triggered by. If null then webhook triggered at account level
 * @param eventName Webhook trigger event name
 * @param requestHeaders 
 */

data class WebhookDto (
    /* ID of the Webhook */
    @Json(name = "id")
    val id: java.util.UUID,
    /* User ID of the Webhook */
    @Json(name = "userId")
    val userId: java.util.UUID,
    /* Does webhook expect basic authentication? If true it means you created this webhook with a username and password. MailSlurp will use these in the URL to authenticate itself. */
    @Json(name = "basicAuth")
    val basicAuth: kotlin.Boolean,
    /* URL of your server that the webhook will be sent to. The schema of the JSON that is sent is described by the payloadJsonSchema. */
    @Json(name = "url")
    val url: kotlin.String,
    /* HTTP method that your server endpoint must listen for */
    @Json(name = "method")
    val method: WebhookDto.Method,
    /* Deprecated. Fetch JSON Schema for webhook using the getJsonSchemaForWebhookPayload method */
    @Json(name = "payloadJsonSchema")
    val payloadJsonSchema: kotlin.String,
    /* When the webhook was created */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime?,
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,
    /* Name of the webhook */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* The inbox that the Webhook will be triggered by. If null then webhook triggered at account level */
    @Json(name = "inboxId")
    val inboxId: java.util.UUID? = null,
    /* Webhook trigger event name */
    @Json(name = "eventName")
    val eventName: WebhookDto.EventName? = null,
    @Json(name = "requestHeaders")
    val requestHeaders: WebhookHeaders? = null
) {

    /**
     * HTTP method that your server endpoint must listen for
     * Values: GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS,TRACE
     */
    enum class Method(val value: kotlin.String) {
        @Json(name = "GET") GET("GET"),
        @Json(name = "HEAD") HEAD("HEAD"),
        @Json(name = "POST") POST("POST"),
        @Json(name = "PUT") PUT("PUT"),
        @Json(name = "PATCH") PATCH("PATCH"),
        @Json(name = "DELETE") DELETE("DELETE"),
        @Json(name = "OPTIONS") OPTIONS("OPTIONS"),
        @Json(name = "TRACE") TRACE("TRACE");
    }
    /**
     * Webhook trigger event name
     * Values: EMAIL_RECEIVED,NEW_EMAIL,NEW_CONTACT,NEW_ATTACHMENT,EMAIL_OPENED,EMAIL_READ,BOUNCE,BOUNCE_RECIPIENT,NEW_SMS
     */
    enum class EventName(val value: kotlin.String) {
        @Json(name = "EMAIL_RECEIVED") EMAIL_RECEIVED("EMAIL_RECEIVED"),
        @Json(name = "NEW_EMAIL") NEW_EMAIL("NEW_EMAIL"),
        @Json(name = "NEW_CONTACT") NEW_CONTACT("NEW_CONTACT"),
        @Json(name = "NEW_ATTACHMENT") NEW_ATTACHMENT("NEW_ATTACHMENT"),
        @Json(name = "EMAIL_OPENED") EMAIL_OPENED("EMAIL_OPENED"),
        @Json(name = "EMAIL_READ") EMAIL_READ("EMAIL_READ"),
        @Json(name = "BOUNCE") BOUNCE("BOUNCE"),
        @Json(name = "BOUNCE_RECIPIENT") BOUNCE_RECIPIENT("BOUNCE_RECIPIENT"),
        @Json(name = "NEW_SMS") NEW_SMS("NEW_SMS");
    }
}

