/**
* MailSlurp API
* MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
*
* The version of the OpenAPI document: 6.5.2
* Contact: contact@mailslurp.dev
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mailslurp.models


import com.google.gson.annotations.SerializedName

/**
 * Result of webhook test request
 * @param url 
 * @param method 
 * @param headers 
 * @param payload 
 */

data class WebhookTestRequest (
    @SerializedName("url")
    val url: kotlin.String,
    @SerializedName("method")
    val method: WebhookTestRequest.Method,
    @SerializedName("headers")
    val headers: kotlin.collections.Map<kotlin.String, kotlin.String>,
    @SerializedName("payload")
    val payload: kotlin.String? = null
) {

    /**
     * 
     * Values: GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS,TRACE
     */
    enum class Method(val value: kotlin.String) {
        @SerializedName(value = "GET") GET("GET"),
        @SerializedName(value = "HEAD") HEAD("HEAD"),
        @SerializedName(value = "POST") POST("POST"),
        @SerializedName(value = "PUT") PUT("PUT"),
        @SerializedName(value = "PATCH") PATCH("PATCH"),
        @SerializedName(value = "DELETE") DELETE("DELETE"),
        @SerializedName(value = "OPTIONS") OPTIONS("OPTIONS"),
        @SerializedName(value = "TRACE") TRACE("TRACE");
    }
}

